# -*- coding: utf-8 -*-
"""DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7JYrTFt8575kHymuqyc4ktUE4fL0j9v
"""

import pandas as pd
import random

# Generate data
names = [f"Student_{i}" for i in range(1, 51)]
roll_numbers = [f"RN{i:03d}" for i in range(1, 51)]
ages = [random.randint(18, 25) for _ in range(50)]
subjects = ["Math", "Science", "English", "History", "Geography"]

# Create subject-marks column with format like "Math-85"
subject_marks = [f"{random.choice(subjects)}-{random.randint(50, 100)}" for _ in range(50)]

# Create DataFrame
df = pd.DataFrame({
    "name": names,
    "roll number": roll_numbers,
    "age": ages,
    "subject-marks": subject_marks
})

# Display DataFrame
df

[df['age'] > 23]

df[df['age'] > 23]

Totalcount_23 = df[df['age'] > 23].shape[0]
print("Number of students over age 23:", Totalcount_23 )

count_math_over_80 = df[
     df['subject-marks'].str.contains("Math") & (
 df['subject-marks'].str.extract(r"(\d+)$").astype(int)[0]> 80 )]

 print("Number of students who scored over 80 in Math:", count_math_over_80.shape[0])

mathscore_over_80 = df[
    df['subject-marks'].str.contains("Math") &
    (df['subject-marks'].str.extract(r"(\d+)$").astype(int)[0] > 80)
]

print("Students who scored over 80 in Math:\n", mathscore_over_80)