# -*- coding: utf-8 -*-
"""DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7JYrTFt8575kHymuqyc4ktUE4fL0j9v
"""

import pandas as pd
import random

# Generate data
names = [f"Student_{i}" for i in range(1, 51)]
roll_numbers = [f"RN{i:03d}" for i in range(1, 51)]
ages = [random.randint(18, 25) for _ in range(50)]
subjects = ["Math", "Science", "English", "History", "Geography"]

# Create subject-marks column with format like "Math-85"
subject_marks = [f"{random.choice(subjects)}-{random.randint(50, 100)}" for _ in range(50)]

# Create DataFrame
df = pd.DataFrame({
    "name": names,
    "roll number": roll_numbers,
    "age": ages,
    "subject-marks": subject_marks
})

# Display DataFrame
df

